permalink: pretty
markdown: rdiscount
pygments: true
lsi: true
exclude: Capfile, Rakefile, scripts, README
source: content
basedomain: http://10.44.200.5:4000
#basedomain: http://7tharochdale.org.uk.dev.nodehost.co.uk
