permalink: pretty
markdown: rdiscount
pygments: true
lsi: true
exclude: Capfile, Rakefile, scripts, README
source: content
basedomain: http://127.0.0.1:4000
#basedomain: http://7tharochdale.dev.nodehost.co.uk