permalink: pretty
markdown: rdiscount
pygments: true
lsi: true
exclude: 7thARochdale.komodoproject, README.md, doshit.py, templates
source: content
basedomain: http://10.44.200.5:4039
server_port: 4039
